<?php

namespace ContainerDTQartU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DBkwhRRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DBkwhRR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DBkwhRR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repoagence' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
        ], [
            'repoagence' => 'App\\Repository\\AgenceRepository',
        ]);
    }
}
