<?php

namespace ContainerXiApsIe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XQeAlCpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xQeAlCp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xQeAlCp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\ClientAgenceRepository', 'getClientAgenceRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ClientAgenceRepository',
        ]);
    }
}
