<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRJPCiBt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRJPCiBt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRJPCiBt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRJPCiBt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRJPCiBt\App_KernelDevDebugContainer([
    'container.build_hash' => 'RJPCiBt',
    'container.build_id' => 'f6c3d851',
    'container.build_time' => 1614223113,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRJPCiBt');
