<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVmaHvbU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVmaHvbU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVmaHvbU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVmaHvbU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVmaHvbU\App_KernelDevDebugContainer([
    'container.build_hash' => 'VmaHvbU',
    'container.build_id' => '70a53a76',
    'container.build_time' => 1615902895,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVmaHvbU');
