<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIA2Yq1J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIA2Yq1J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIA2Yq1J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIA2Yq1J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIA2Yq1J\App_KernelDevDebugContainer([
    'container.build_hash' => 'IA2Yq1J',
    'container.build_id' => 'ea4d7f9c',
    'container.build_time' => 1614294665,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIA2Yq1J');
