<?php

namespace Container0q5zr0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ifo7yJ7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ifo7yJ7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ifo7yJ7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repotransaction' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
        ], [
            'repotransaction' => 'App\\Repository\\TransactionRepository',
        ]);
    }
}
