<?php

namespace Container0q5zr0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionDataPersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataPersister\TransactionDataPersister' shared autowired service.
     *
     * @return \App\DataPersister\TransactionDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/ContextAwareDataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataPersister/TransactionDataPersister.php';
        include_once \dirname(__DIR__, 4).'/src/Services/TransactionServices.php';

        return $container->privates['App\\DataPersister\\TransactionDataPersister'] = new \App\DataPersister\TransactionDataPersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), new \App\Services\TransactionServices(), ($container->privates['App\\Repository\\AgenceRepository'] ?? $container->load('getAgenceRepositoryService')), ($container->privates['App\\Repository\\ClientAgenceRepository'] ?? $container->load('getClientAgenceRepositoryService')));
    }
}
