<?php

namespace ContainerAIRPuxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FUFcA8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F_UFcA8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F_UFcA8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ClientAgenceController::get_clients' => ['privates', '.service_locator.xQeAlCp', 'get_ServiceLocator_XQeAlCpService', true],
            'App\\Controller\\TransactionController::get_transaction' => ['privates', '.service_locator.ifo7yJ7', 'get_ServiceLocator_Ifo7yJ7Service', true],
            'App\\Controller\\TransactionController::get_transaction_by_user' => ['privates', '.service_locator.ifo7yJ7', 'get_ServiceLocator_Ifo7yJ7Service', true],
            'App\\Controller\\UserController::get_agence' => ['privates', '.service_locator.DBkwhRR', 'get_ServiceLocator_DBkwhRRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ClientAgenceController:get_clients' => ['privates', '.service_locator.xQeAlCp', 'get_ServiceLocator_XQeAlCpService', true],
            'App\\Controller\\TransactionController:get_transaction' => ['privates', '.service_locator.ifo7yJ7', 'get_ServiceLocator_Ifo7yJ7Service', true],
            'App\\Controller\\TransactionController:get_transaction_by_user' => ['privates', '.service_locator.ifo7yJ7', 'get_ServiceLocator_Ifo7yJ7Service', true],
            'App\\Controller\\UserController:get_agence' => ['privates', '.service_locator.DBkwhRR', 'get_ServiceLocator_DBkwhRRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ClientAgenceController::get_clients' => '?',
            'App\\Controller\\TransactionController::get_transaction' => '?',
            'App\\Controller\\TransactionController::get_transaction_by_user' => '?',
            'App\\Controller\\UserController::get_agence' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ClientAgenceController:get_clients' => '?',
            'App\\Controller\\TransactionController:get_transaction' => '?',
            'App\\Controller\\TransactionController:get_transaction_by_user' => '?',
            'App\\Controller\\UserController:get_agence' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
